apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ew75rpdbq-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ew75rpdbq-nodejs 
  name: ew75rpdbq-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ew75rpdbq-nodejs 
